#ifndef ActKinStabilizerService_idl
#define ActKinStabilizerService_idl

#include "ExtendedDataTypes.idl" // openrtm
#include "actkin_stabilizer_msgs/idl/ActKinStabilizer.idl"

module actkin_stabilizer
{
  enum EmergencyCheckMode {
    NO_CHECK,
    CM
  };

  interface ActKinStabilizerService
  {
    struct ContactableRegionIdl {
      string link; // URDF link name
      RTC::Pose3D localPose; // link local frame
      actkin_stabilizer_msgs::Region3D region; // localPose frame
    };

    struct ActKinStabilizerParam
    {
      // ActKinStabilizer
      /// 含まれない場合、tauはrefの値をそのまま出力する(writeOutputPort時にref値で上書き). IKでは動かさない.
      sequence<string> controllableJoints;

      // ActToGenFrameConverter
      /// [roll, pitch, yaw]. rootLink Frame. Actual robotのrootLinkの姿勢に加えるオフセット. IMUの取り付け位置のオフセットを考慮するためのものではない(それはモデルファイルを変えれば良い). 全身のキャリブのずれなど次第に出てくるなにかしらのずれをごますためのもの. 本来このようなパラメータは必要ないのが望ましいが、実用上は確かに必要.
      sequence<double, 3> rpy_offset;

      // 接触可能点
      ContactableRegionIdl contactableRegion;
      // contactのZ軸のthre (rad)
      double normalAngle;

      // ロボット重心のZ方向重み. default 1.0: 0以上.
      double wZ;

      // EE 位置 Pゲイン. - K * 位置誤差を目標加速度とする. 0以上
      double Kp;
      // EE 位置 Dゲイン. - D * 相対速度を目標加速度とする. 0以上
      double Dp;
      // K * 位置誤差に対するlimit. 0以上.
      double limitp;
      // EE 姿勢 Pゲイン. - K * 姿勢誤差を目標加速度とする. 0以上
      double Kr;
      // EE 姿勢 Dゲイン. - D * 相対速度を目標加速度とする. 0以上
      double Dr;
      // K * 姿勢誤差に対するlimit. 0以上.
      double limitr;

      // horizonの最小時間[s]
      double minHorizonTime;

      // 関節Pゲイン. - K * 角度誤差を目標加速度とする. 0以上
      double Kq;
      // 関節Dゲイン. - D * 相対速度を目標加速度とする. 0以上
      double Dq;
      // K * 角度誤差に対するlimit. 0以上.
      double limitq;
      // 関節角度の重み. IKで動かしたくない関節は大きくする. 全く動かしたくないなら、controllableJointsを使うこと. 0以上. default 1.0
      double wq;

    };

    boolean startStabilizer();
    boolean stopStabilizer();

    boolean setActKinStabilizerParam(in ActKinStabilizerParam i_param);
    boolean getActKinStabilizerParam(out ActKinStabilizerParam i_param);

    // boolean setRefEE(in actkin_stabilizer_msgs::RefEESequence refEEPose);
    // boolean setRefVRP(in actkin_stabilizer_msgs::RefVRPIdl refVRP);
    // boolean setRefContact(in actkin_stabilizer_msgs::RefContactSequence refContact);
    // boolean setRefq(in actkin_stabilizer_msgs::RefqIdl refq);
    // boolean setRefState(in actkin_stabilizer_msgs::RefStateIdl refState);
  };

  // enum Priority {
  //   EE_MIDIUM, // 通常
  //   EE_LOW, // 低優先度タスク
  //   EE_HIGH // 歩行時の遊脚
  // };

  // enum EEMode {
  //   KEEP_PREV, // to controll only
  //   NOT_CARED,
  //   AIR,
  //   // REL_LINK,
  //   TO_CONTACT,
  //   TO_AIR,
  //   CONTACT
  // };

};

#endif
